In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 10 10:37:33 2024

@author: HP
"""

import numpy as np

empty_array_2d = np.empty((3, 3))
print(empty_array_2d)


full_array_2d = np.full((3, 3), 5)
print(full_array_2d)

print('-------------------------------------------------------------')

print(' #q2')
# -*- coding: utf-8 -*-

import numpy as np

rand_num = np.random.normal(0, 1, 25)

print("25 random numbers from a standard normal distribution:")

print(rand_num)

print('-------------------------------------------------------------')

print(' #q3')
import numpy as np


arr = np.array([3, 1, 9, 7])
arr1 = np.array([2, 6, 4, 8])
arr2 = np.dot(arr, arr1)
print("Dot Product  : \n", arr2)
print('-------------------------------------------------------------')
print(' #q4')

import numpy as np


nums = np.array([[3, 7, 1],
              [10, 3, 2],
              [5, 6, 7]])

print("Original array:")
print(nums)


print("\nSort the said array by row in ascending order:")
print(np.sort(nums))


print("\nSort the said array by column in ascending order:")
print(np.sort(nums, axis=0))

print("\nSort the said array in  ascending order:")
print(np.sort(nums, axis=None))

print('-------------------------------------------------------------')
print(' #q5')

import numpy as np

Input = [np.array([1, 2, 3]),
         np.array([4, 5, 6]),
         np.array([7, 8, 9])]

Output = []

for i in range(len(Input)):
   Output.append(np.mean(Input[i]))

print(Output)
print('-------------------------------------------------------------')

print(' #q6')
import numpy as np


# Original Array
array = np.array(['PHP C# Python C Java C++'], dtype=np.str_)
print(array)

# Split the element of the said array
# with spaces
sparr = np.char.split(array)
print(sparr)


[[4.71776746e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
-------------------------------------------------------------
 #q2
25 random numbers from a standard normal distribution:
[-0.73109819  1.44438781  0.58100234  0.91786118  0.04163651  0.85885493
 -0.97647579  1.26214987 -0.91159663  0.15916467 -1.04927755  0.66404349
 -1.44717752 -0.32255845 -0.6372145   0.0317467  -0.69497738 -0.86885983
  0.15802518  2.51089983 -0.92716407 -0.4651908   0.57971897 -0.93018768
 -1.12649565]
-------------------------------------------------------------
 #q3
Dot Product  : 
 104
-------------------------------------------------------------
 #q4
Original array:
[[ 3  7  1]
 [10  3  2]
 [ 5  6  7]]

Sort the said array by row in ascending order:
[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]

Sort the said array by column in ascending order:
[[ 3  3  1]
 [ 5  6  2]
 [10  7  7]]

Sort the